services:
  telebot:
    build: .
    container_name: telebot-worker
    restart: always
    volumes:
      - ./reports:/app/reports
      - ./media_cache:/app/media_cache
      - ./telebot.session:/app/telebot.session
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
